[theme]
base = "light"
primaryColor = "#787b86"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#131722"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
